// <auto-generated />
using System;
using CardReg_CRUD_AngularFront.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardReg_CRUD_AngularFront.Migrations
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardReg_CRUD_AngularFront.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CVC")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpireMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpireYear")
                        .HasColumnType("int");

                    b.Property<string>("HolderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36fa4f1f-c94d-4f86-83f3-f15c383884e3"),
                            CVC = 123,
                            CardNumber = "39483843499999",
                            ExpireMonth = 1,
                            ExpireYear = 2026,
                            HolderName = "Ermin Husic"
                        },
                        new
                        {
                            Id = new Guid("31f18d7c-2058-40a5-9ade-3234b18234b6"),
                            CVC = 456,
                            CardNumber = "5234567890123456",
                            ExpireMonth = 2,
                            ExpireYear = 2025,
                            HolderName = "Anna Svensson"
                        },
                        new
                        {
                            Id = new Guid("99cc1a5b-0dec-4dc2-9b87-de3456b0fba1"),
                            CVC = 789,
                            CardNumber = "6011123456789012",
                            ExpireMonth = 3,
                            ExpireYear = 2024,
                            HolderName = "Björn Karlsson"
                        },
                        new
                        {
                            Id = new Guid("6efcca8c-599e-47f5-a0ef-cb15dbc77f56"),
                            CVC = 321,
                            CardNumber = "4000056655665556",
                            ExpireMonth = 4,
                            ExpireYear = 2027,
                            HolderName = "Caroline Lindberg"
                        },
                        new
                        {
                            Id = new Guid("b2ac5c39-b602-4042-b654-174cfd586ce8"),
                            CVC = 654,
                            CardNumber = "3566002020360505",
                            ExpireMonth = 5,
                            ExpireYear = 2023,
                            HolderName = "David Ek"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
